#!/bin/sh

# Script that convert update the history from a GIT repository
# that was imported from CVS.

# The first part convert the commit message encoding from ISO-8859-1 to UTF-8.
# The second part update my name to reflect my new identity (no nickname now !).
git filter-branch -f --msg-filter '
while read LINE
do
	echo $LINE | iconv -f ISO-8859-1 -t utf-8
done
' --commit-filter '
if [ "$GIT_COMMITTER_NAME" = "cid" ];
then
	GIT_COMMITTER_NAME="Sylvain Filteau";
	GIT_AUTHOR_NAME="Sylvain Filteau";
	GIT_COMMITTER_EMAIL="cidsphere@gmail.com";
	GIT_AUTHOR_EMAIL="cidsphere@gmail.com";
	git commit-tree "$@";
else
	git commit-tree "$@";
fi' HEAD
